language: node_js
node_js:
  - 10
  - 12
cache:
  directories:
    - "node_modules"
script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
